Fix link on popup
yperess/gerrit-chrome-extension pull request #17
Opened 2016-10-17 12:49 UTC by sunglim

Fixes https://github.com/yperess/gerrit-chrome-extension/issues/16

The core change is
`url: BASE_URL + '/' + change._number` -> `url: BASE_URL + '/' + this.textContent`

and style fix.

2016-10-17 13:26 UTC, yperess requested changes

2016-10-17 13:26 UTC, yperess commented on extension/popup.js
> +	var BASE_URL = localStorage['api_endpoint'];
nit: indent?

2016-10-17 13:26 UTC, yperess commented on extension/popup.js
> -    a.textContent = 'cl/' + change._number;
Please keep 'cl/' this is a part of another feature I'm intending to add, sorry for not writing up the issue before, see #18.

Instead why don't we do:
```javascript
a.addEventListener('click', function(e) {
  chrome.tabs.update(null, {
    url: BASE_URL + '/' + this.getAttribute('change-id');
  });
})
a.setAttribute('change-id', change._number)
```

2016-10-17 18:29 UTC, sunglim commented
I will fix at office (From home i'm not able to connect to company gerrit. so, i can't test).

2016-10-18 01:15 UTC, sunglim reviewed
Thanks for the review

2016-10-18 01:15 UTC, sunglim commented on extension/popup.js
> +	var BASE_URL = localStorage['api_endpoint'];
Done.

2016-10-18 01:15 UTC, sunglim commented on extension/popup.js
> -    a.textContent = 'cl/' + change._number;
Done.

2016-10-18 01:16 UTC, sunglim commented
PTAL.

2016-10-18 01:37 UTC, merged